#启动端口号
server:
  port: 8077

#订单服务地址
spring:
  application:
    name: dj_video

#数据库配置  jdbc 6.0 for java 6.0及以上，都需要设置serverTimezone，否则会报错
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xdclass?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver

#属性字段映射  下划线转成驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#===========================微信配置==========================#
 #公众号
wxpay:
  appid: wx4f4374e47a360c22
  appsecret: 554801238f17fdsdsdd6f96b382fe548215e9
  #微信支付回调
  callback: 16web.tunnel.qydev.com/v1/wechat/order/callback
  key: 650477235c5e0882a0470e94accd9f6f
  mer_id: 1355406302
#微信开放平台配置
wxopen:
  appid: wx025575eac69a2d5b
  appsecret: deeae310a387fa9d3e8f3830ce64caac

#重定向url
  #微信登录回调
  redirect_url: http://eb7cdf9a.ngrok.io/api/v1/wechat/user/callback

